// Pest grammar for HLHDL-like syntax

program = _{ SOI  ~ (outer_statement +)* ~ EOI }
outer_statement = _{ function_def}

function_def= { "fn" ~ identifier ~ "(" ~ params? ~ ")" ~ function_body }
function_body = { "{" ~ (inner_statement +)* ~ "}" }
inner_statement = _{ inner_statements_with_semicolon | if }
inner_statements_with_semicolon = _{ (return_statement | assignment | function_call) ~ ";" }
params = { param ~ ("," ~ param)* }
param = { identifier ~ ":" ~ type }

function_call = { identifier ~ "(" ~ param_list? ~ ")" }
param_list = { expression ~ ("," ~ expression)* }

type = { "String" | "Int"}

assignment = _{ "let " ~ identifier ~ "=" ~ expression }
// anything that can be coerced to a value
expression = {
    dyadic
    | primary_expression
}
dyadic = { primary_expression ~ (operator ~ primary_expression)* }
primary_expression = _{ function_call | paren_expression | identifier | value }
paren_expression = _{ "(" ~ expression ~ ")" }

// any word that starts with a letter and is followed by letters or numbers
identifier = _{ !reserved ~ primary_identifier }
primary_identifier = @{ !ASCII_DIGIT ~ (ASCII_ALPHA | ASCII_DIGIT | "_")* }
reserved = _{ "fn" | "if" | "else" | "return" | "let" | "String" | "int" }

operator = _{ "+" | "-" | "*" | "/" | "%" | "==" | "!=" | "<" | ">" | "<=" | ">=" }
value = _{ ASCII_DIGIT+ | string }
string = _{ "\"" ~ (!"\"" ~ ANY)* ~ "\"" }


if = { "if" ~ expression ~ "{" ~ (inner_statement +)* ~ "}" ~ ("else" ~ "{" ~ (inner_statement +)* ~ "}")? }
return_statement = { "return" ~ expression }

WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT = _{ ("/*" ~ (!"*/" ~ ANY)* ~ "*/") | ("//" ~ (!"\n" ~ ANY)*) }

